name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
        current_dir="$(basename "$PWD")"

        if [ -d "$current_dir" ]; then
          cd "$current_dir"
          cargo run
          cd ../
        else
          echo "No project folder was found: $current_dir"
        fi
    - name: Run tests
      run: |
        current_dir="$(basename "$PWD")"

        if [ -d "$current_dir" ]; then
          cd "$current_dir"
          cargo test
          cd ../
        else
          echo "No project folder was found: $current_dir"
        fi
    - name: Run formatter
      run: |
        current_dir="$(basename "$PWD")"

        if [ -d "$current_dir" ]; then
          cd "$current_dir"
          cargo fmt
          cd ../

          if [ -n "$(git status --porcelain)" ]; then
            git config user.email "actions@example.com"
            git config user.name "GitHub Actions"

            git checkout -b formatter
            git add .
            git commit -m "Format code"
            git push origin formatter

            gh pr create --base main --head formatted-branch --title "Format code" --body "This pull request contains formatted code."
            echo "Formatted repo and opened pr"
          else
            echo "Nothing to format"
        else
          echo "No project folder was found: $current_dir"
        fi
