name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
        current_dir="$(basename "$PWD")"

        if [ -d "$current_dir" ]; then
          cd "$current_dir"
          cargo run
          cd ../
        else
          echo "No project folder was found: $current_dir"
        fi
    - name: Run tests
      run: |
        current_dir="$(basename "$PWD")"

        if [ -d "$current_dir" ]; then
          cd "$current_dir"
          cargo test
          cd ../
        else
          echo "No project folder was found: $current_dir"
        fi
    - name: Run formatter
      run: |
        current_dir="$(basename "$PWD")"
        
        if [ -d "$current_dir" ]; then
          cd "$current_dir"
          cargo fmt
          cd ../
        else
          echo "No project folder was found: $current_dir"
        fi
